name: physio_calc
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.7.2
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0
  flutter_form_builder: ^10.1.0
  permission_handler: ^12.0.1
  file_picker: ^10.2.1
  shared_preferences: ^2.0.16
  form_builder_validators: ^11.2.0
  pdf: ^3.9.0
  path_provider: ^2.0.12
  flutter_flavor: ^3.1.1
  url_launcher: ^6.1.10
  package_info_plus: ^8.3.0
  open_filex: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_native_splash:
  color: "#0066B3"
  image: "assets/icons/icon-launcher.png"
  android: true
  ios: true
  android_12:
    image: "assets/icons/icon-launcher.png"
    icon_background_color: "#0066B3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-launcher.png"
