name: physio_calc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  package_info: ^2.0.2
  flutter_form_builder: ^7.7.0
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  open_file_plus: ^3.4.0
  shared_preferences: ^2.0.16
  form_builder_validators: ^8.4.0
  pdf: ^3.9.0
  path_provider: ^2.0.12
  flutter_flavor: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
